Added Contributions and Research fields
aseic/aseic.github.io pull request #9
Opened 2022-05-23 00:49 UTC by Vivallo04

Hello, I added these two new sections (research #8 and contribution #6), I think it's necessary to hear as frequently as needed from the community to allow people to get used to this site. Hear what they want and encourage them to really use the site and also to contribute.

Hope you like the new changes, I'm open to getting some feedback.

2022-05-29 05:50 UTC, alejandrodp commented
Gracias por los comentarios, es cierto todo lo que dice, es una parte muy importante del TEC la investigación por lo que sería excelente tener una sección para eso como se ha discutido en dichos issues. Lamento que tardara tanto en revisar sus aportes.

Por otra parte, creo que sería mejor mantener los commits, issues y demás elementos de documentación en español, sé que es algo común manejarlos en inglés pero considero que para que la mayoría de integrantes de CE puedan manejarse mejor a través de toda esa documentación sería mejor mantener el lenguaje principal en español. ¿Qué le parece?

2022-05-29 18:04 UTC, alejandrodp requested changes, later dismissed

2022-05-29 18:04 UTC, alejandrodp commented on src/contribuciones.md
> +¿Tienes una pregunta? En vez de abrir un nuevo issue, puedes hacer la pregunta en el grupo de [Comunidad CE](https://t.me/ComunidadCeTec) en Telegram.
Aquí se puede añadir que para cualquier pregunta también se puede contactar a los miembros de la junta directiva. Entonces se podría reescribir de la siguiente manera:

```suggestion
¿Tienes una pregunta? En vez de abrir un nuevo issue, puedes hablar con cualquier miembro de la [junta directiva](representacion_estudiantil.md#junta-directiva) o también puedes hacer la pregunta en el grupo de [Comunidad CE](https://t.me/ComunidadCeTec) en Telegram.
```

2022-05-29 18:04 UTC, alejandrodp commented on src/investigaciones.md
> +# Investigaciones
Creo que aquí es importante destacar que pueden ser investigaciones de profesores también, es decir, debería ser una sección que acepte cualquier tipo de proyecto de investigación. Entonces con lo que menciona en las templates hice este [formulario](https://forms.gle/HZQUFpBuG27k5u4x5). Si gusta verlo puede darme feedback para mejorar y así cambiar esta sección para que incluya el enlace a dicho fomulario y que la gente pueda empezar a agregar proyectos. También se podrían ir agregando proyectos conocidos para motivar a la gente y mejorar la utilidad del sitio.

2022-05-29 23:17 UTC, Vivallo04 commented on src/investigaciones.md
> +# Investigaciones
Me parece bastante bien lo de añadir las investigaciones de profesores, me parece que es bastante importante. Respecto al form, lo veo, pienso que se podría añadir una sección donde pregunte si están buscando/aceptando personas para que colaboren con la investigación. Y si se puede mejorar el formato de respuesta en la sección de "participantes", pienso que estaría bien, como añadir más líneas, una por participante, en vez de que sea una sola.

2022-06-10 15:42 UTC, Vivallo04 commented
Hay algún otro cambio que deba hacer?

2022-06-10 20:29 UTC, alejandrodp commented
Yo creo que solo queda agregar a la parte de investigaciones el enlace al form (https://forms.gle/xHzHPKD4MvzqAp5z8). Por ahora se puede quedar así, en semana 18 ya vendré a colocarle más información y afinar esta parte si hace falta, si quiere ayudar le agradecería mucho. Una vez puesto lo del form ya le hago merge.

2022-06-10 20:30 UTC, alejandrodp commented
La idea es ojalá agregarle suficiente información para que de ahora en adelante la gente pueda venir aquí y se pueda redirigir aquí de una vez cuando pregunten en comunidad ce

2022-06-19 04:39 UTC, merged